apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    app: nginxhello
  name: single-default-backend-ingress
  annotations:
    fluxcd.io/ignore: "false"
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: ingress-nginx
  rules:
    - host: nginxhello.localdev.me
      http:
        paths:
          - path: /
            backend:
              serviceName: nginxhello
              servicePort: 80
